User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
Python interpreter path: ~/Apps/anaconda3/bin/python
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py
cwd: ~/work/Projects/FlappyBird
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py
cwd: ~/work/Projects/FlappyBird
Starting Pylance language server.
Error 2021-07-16 14:27:53: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/fenris/work/Projects/FlappyBird/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/fenris/work/Projects/FlappyBird/.vscode/settings.json')
	at _handleError (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:167834)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/fenris/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/home/fenris/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /home/fenris/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/fenris/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/home/fenris/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py
cwd: ~/work/Projects/FlappyBird
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py
cwd: ~/work/Projects/FlappyBird
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py.39fc11e9fc6ee80c7f2047c585c18141.tmp
cwd: ~/work/Projects/FlappyBird
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py.39fc11e9fc6ee80c7f2047c585c18141.tmp
cwd: ~/work/Projects/FlappyBird
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py.39fc11e9fc6ee80c7f2047c585c18141.tmp
cwd: ~/work/Projects/FlappyBird
> ~/Apps/anaconda3/bin/python -m autopep8 --diff ~/work/Projects/FlappyBird/main.py.39fc11e9fc6ee80c7f2047c585c18141.tmp
cwd: ~/work/Projects/FlappyBird
Error 2021-07-16 14:36:26: Error while running worker[Worker 1]. undefined
Error 2021-07-16 14:36:26: Error while running worker[Worker 2]. undefined
